### PR TITLE
Update precommit

### PR DESCRIPTION
**Pull request by mamueluth**
*Updated pre-commit hooks to newer version
* exclude `/docs/_themes/*` (spellcheck, white space fixing...)

### CODE REVIEW

**Comment by mamueluth** [comment]
I think probably that for `ament_cpplint ` ,`check-ast', `ament_copyright` ... all files that have by design an invalid syntax should be ignored, otherwise pre-commit is going to fail if rerun with -a flag. E.G . py files in /templates which include $LICENSE$

**Comment by mamueluth** [comment]
What are your thoughts on replacing the `ament_*` commands in `.pre-commit-config.yaml` with hooks provided by pre-commit? I think otherwise, we make pre-commit dependent on the installed ros-version, though iI am not sure if that's a problem...

**Comment by destogl** [comment]
This version of pre-commit config is created for the ROS repositories. Of course, one can use it otherwise, but it's not the main target. I tried before to replace commands with “upstream” commands but didn't find any good configuration. We can open an issue for this and check this later.

The idea is that one has to always have their workspace source before executing these commands.

Let's make it green first without much tweaking then needed, please.

**Comment by destogl** [comment]
@mergifyio backport foxy

**Pull request merged**
